package com.glovendorproject.glovendor_backend_dev.service;


import com.glovendorproject.glovendor_backend_dev.entity.Admin;
import com.glovendorproject.glovendor_backend_dev.entity.Report;
import com.glovendorproject.glovendor_backend_dev.repo.ReportRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class ReportService {

    private final ReportRepository reportRepository;

    public ReportService(ReportRepository reportRepository) {
        this.reportRepository = reportRepository;
    }

    // Create or upload a report
    public Report saveReport(Report report) {
        return reportRepository.save(report);
    }

    // Get all reports
    public List<Report> getAllReports() {
        return reportRepository.findAll();
    }

    // Get reports generated by a specific admin
    public List<Report> getReportsByAdmin(Admin admin) {
        return reportRepository.findByGeneratedBy(admin);
    }

    // Get report by ID
    public Optional<Report> getReportById(Long id) {
        return reportRepository.findById(id);
    }

    // Delete report
    public void deleteReport(Long id) {
        reportRepository.deleteById(id);
    }
}
