package com.glovendorproject.glovendor_backend_dev.repo;


import com.glovendorproject.glovendor_backend_dev.entity.Admin;
import com.glovendorproject.glovendor_backend_dev.entity.Report;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ReportRepository extends JpaRepository<Report, Long> {
    // Find all reports generated by a specific admin
    List<Report> findByGeneratedBy(Admin admin);
}
